running_translations = [
    "Running",          # English (US)
    "Wird ausgeführt",  # German (Germany)
    "En cours d’exécution",  # French (France)
    "En ejecución",     # Spanish (Spain)
    "In esecuzione",    # Italian (Italy)
    "Em execução",      # Portuguese (Brazil)
    "Bezig",            # Dutch (Netherlands)
    "Kör",              # Swedish (Sweden)
    "Kører",            # Danish (Denmark)
    "Suoritetaan",      # Finnish (Finland)
    "Kjører",           # Norwegian (Norway)
    "W trakcie",        # Polish (Poland)
    "Запущено",         # Russian (Russia)
    "正在运行",           # Chinese (Simplified)
    "実行中",             # Japanese (Japan)
    "실행 중",            # Korean (South Korea)
    "قيد التشغيل",        # Arabic (Saudi Arabia)
    "Çalışıyor",         # Turkish (Turkey)
    "Probíhá",          # Czech (Czech Republic)
    "Fut",              # Hungarian (Hungary)
    "În execuție",      # Romanian (Romania)
    "Εκτελείται",        # Greek (Greece)
    "กำลังทำงาน",         # Thai (Thailand)
    "Sedang berjalan",   # Indonesian (Indonesia)
    "Sedang berjalan",   # Malay (Malaysia)
    "Đang chạy",        # Vietnamese (Vietnam)
    "Tumatakbo",         # Filipino (Philippines)
    "चल रहा है",          # Hindi (India)
    "চালানো হচ্ছে",       # Bengali (India)
    "இருக்கிறது",        # Tamil (India)
    "నడుస్తోంది",         # Telugu (India)
    "चालू आहे",          # Marathi (India)
    "ચાલી રહ્યું છે",       # Gujarati (India)
    "ನಡೀತಿದೆ",           # Kannada (India)
    "നടക്കുന്നു",          # Malayalam (India)
    "ਚੱਲ ਰਿਹਾ ਹੈ",       # Punjabi (India)
    "ଚାଲିଛି",           # Oriya (India)
    "চলিছে",            # Assamese (India)
    "चलिरहेको छ",        # Nepali (Nepal)
    "දැක්කා",           # Sinhala (Sri Lanka)
    "ក",                # Khmer (Cambodia) — appears truncated
]
